### ISSUE TITLE
unique_together adding only key, not a constraint in sqlite db

### ISSUE THREAD

**Issue by rhoerbe** [identinetics/PVZDweb#20]
https://github.com/identinetics/PVZDweb/blob/dev_rh/portaladmin/models/MDstatement.py#L24

It is still possible to add duplicate entries.

e.g. add tests/saml/sidned_ed/22_idp22_identinetics_valid.xml. twice.

**Comment by LennyLip** [comment]
I think Django enforced unique_together only at the database level, and I am not sure that SQLite supports this. It needs to check, but I don't see  any 
`"CONSTRAINT constraint_name UNIQUE (uc_col1, uc_col2, ... uc_col_n)"`
SQL constructions.
![uniqiue](https://user-images.githubusercontent.com/955994/49380175-08991900-f722-11e8-8fb0-7e505d7be551.png)

**Comment by rhoerbe** [comment]
waiting for dockerized version with Postgres DB

**Comment by rhoerbe** [comment]
added code in save to disallow adding duplicates. This is kind of a fix, assuming that nobody is passing MDSatement.save().
